Gyeongjo119/mouem-zip

- backend/.idea/vcs.xml
- backend/database.sql
> chore: database.sql 쿼리 추가

- backend/database.sql
> register_analysis_result 테이블 유니크 키 추가
> chore: database.sql 쿼리 수정

- backend/src/main/java/org/scoula/config/RootConfig.java
- backend/src/main/java/org/scoula/config/ServletConfig.java
- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/MortgageInfo.java
- backend/src/main/java/org/scoula/register/service/MortgageInfoService.java
- backend/src/main/java/org/scoula/register/service/TabulaService.java
close #16 
register 패키지 추가 후 controller, service, dto 분리
> [chore] register 패키지 추가

- frontend/src/pages/category/CategoryAll.vue
- frontend/src/pages/category/CategoryManager.vue
- frontend/src/pages/special-contracts/SpecialContractsAdd.vue
- frontend/src/pages/special-contracts/SpecialContractsEdit.vue
- frontend/src/pages/special-contracts/SpecialContractsManager.vue
- frontend/src/pages/term/TermManager.vue
- frontend/src/router/index.js
> 관련된 이슈 번호를 적어주세요. : close #29 
- 특약사항 관리 페이지 추가
- 관리 페이지 목록 페이지네이션 추가
(선택)
> [feat] 특약사항 관리자 페이지 구현

- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/InjunctionDTO.java
- backend/src/main/java/org/scoula/register/service/AuctionServiceImpl.java
- backend/src/main/java/org/scoula/register/service/InjunctionService.java
- backend/src/main/java/org/scoula/register/service/InjunctionServiceImpl.java
- backend/src/main/java/org/scoula/register/service/MortgageServiceImpl.java
- backend/src/main/java/org/scoula/register/service/ProvisionalRegistrationServiceImpl.java
- backend/src/main/java/org/scoula/register/service/ProvisionalSeizureServiceImpl.java
- backend/src/main/java/org/scoula/register/service/SeizureServiceImpl.java
- backend/src/main/java/org/scoula/register/util/RegisterUtils.java
- frontend/src/pages/SafetyDiagnosis.vue
close #32 #35 
- 가처분 정보 추출
- 순위번호
- 등기목적
- 등기원인
- 채권자 또는 권리자
- 중복되는 코드에 대해서 `RegisterUtil` 클래스를 통해 관리
말소된 내역에 대해서 추가되지 않는 부분 확인 완료
> [feat] 가처분 정보 추출 구현

- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/TrustDTO.java
- backend/src/main/java/org/scoula/register/service/AuctionServiceImpl.java
- backend/src/main/java/org/scoula/register/service/TrustService.java
- backend/src/main/java/org/scoula/register/service/TrustServiceImpl.java
- frontend/src/pages/SafetyDiagnosis.vue
close #34
신탁등기 정보 추출
- 순위번호
- 등기목적
- 등기원인
- 수탁자
신탁등기 또한 전세권설정과 마찬가지로 실재 기재된 등기부등본을 찾기 힘들어 테스트용 pdf 작성해서 테스트했습니다.
> [feat] 신탁등기 정보 추출 구현

- backend/src/main/java/org/scoula/config/RootConfig.java
- backend/src/main/java/org/scoula/specialcontractrecommendation/controller/SpecialContractRecommendationController.java
- backend/src/main/java/org/scoula/specialcontractrecommendation/domain/SpecialContractRecommendationDTO.java
- backend/src/main/java/org/scoula/specialcontractrecommendation/mapper/SpecialContractRecommendationMapper.java
- backend/src/main/java/org/scoula/specialcontractrecommendation/service/SpecialContractRecommendationService.java
- backend/src/main/java/org/scoula/specialcontractrecommendation/service/SpecialContractRecommendationServiceImpl.java
- backend/src/main/resources/org/scoula/specialcontractrecommendation/mapper/SpecialContractRecommendationMapper.xml
- frontend/src/pages/special-contracts/SpecialContractsRecommendation.vue
- frontend/src/stores/specialRecommendationStore.js
> #48
> DB연동 및 백엔드 작업
> 프론트 더미 데이터 하드코딩 삭제, DB 연동 완료
> <img width="2483" height="567" alt="image" src="https://github.com/user-attachments/assets/e574c2e6-5991-4600-84e4-174e05094b7d" />
> <img width="2548" height="730" alt="image" src="https://github.com/user-attachments/assets/6edc8278-2f00-472d-adf8-b49e71e1179b" />
> feat: 특약 사항 DB연동 및 백엔드 작업

- backend/database.sql
- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/AuctionDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/InjunctionDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/JeonseRightDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/MortgageDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/ProvisionalRegistrationDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/ProvisionalSeizureDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/RegisterAnalysisResponse.java
- backend/src/main/java/org/scoula/register/domain/dto/SeizureDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/TrustDTO.java
- backend/src/main/java/org/scoula/register/service/AuctionServiceImpl.java
- backend/src/main/java/org/scoula/register/service/InjunctionServiceImpl.java
- backend/src/main/java/org/scoula/register/service/JeonseRightServiceImpl.java
- backend/src/main/java/org/scoula/register/service/MortgageServiceImpl.java
- backend/src/main/java/org/scoula/register/service/ProvisionalRegistrationServiceImpl.java
- backend/src/main/java/org/scoula/register/service/ProvisionalSeizureServiceImpl.java
- backend/src/main/java/org/scoula/register/service/SeizureServiceImpl.java
- backend/src/main/java/org/scoula/register/service/TrustServiceImpl.java
- backend/src/main/java/org/scoula/register/util/RegisterUtils.java
- frontend/src/pages/SafetyDiagnosis.vue
close #50 #51 #52 
- 등기부등본 불러오는 내역에서 등기목적 부분을 접수 부분에서 접수일자로 가져오는 것으로 변경했습니다.
- 또한 말소 내역을 확인하기 위해 말소 여부 부분도 추가했습니다.
- 해당 요소가 바뀐 뒤 확인된 위험요소가 json 타입으로 읽어오는지 확인했습니다.
- 멘토링 후 DB 변경 사항도 반영했습니다.
- 삭제 여부 컬럼 추가
테이블 생성에 관해서 오류는 발생하지 않았습니다.
등기부등본 위험 요소 읽어오는 내역 또한 변경 후 잘 읽어오는 것도 확인했습니다.
> [feat] 등기부등본 위험 요소 json으로 변환

- backend/database.sql
- backend/src/main/java/org/scoula/config/ObjectMapperConfig.java
- backend/src/main/java/org/scoula/config/RootConfig.java
- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/RegistryRating.java
- backend/src/main/java/org/scoula/register/domain/dto/RegisterDTO.java
- backend/src/main/java/org/scoula/register/mapper/RegisterMapper.java
- backend/src/main/java/org/scoula/register/service/TabulaService.java
- backend/src/main/resources/org/scoula/register/mapper/RegisterMapper.xml
close #55 
등기부등본 분석 테이블에 분석 내용 저장하는 기능을 구현했습니다.
현재 테이블에 추가할 때 `userId`, `address`, `registryRating`, `status` 변수는 임의로 값을 지정해주고 진행했습니다.
`risks`에 저장된 내용을 읽어올 수 있는지 테스트했습니다.
> [feat] 등기부등본 분석 테이블에 저장 구현

- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/AuctionDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/DatedCanceledItem.java
- backend/src/main/java/org/scoula/register/domain/dto/InjunctionDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/JeonseRightDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/MortgageDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/ProvisionalRegistrationDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/ProvisionalSeizureDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/SeizureDTO.java
- backend/src/main/java/org/scoula/register/domain/dto/TrustDTO.java
- backend/src/main/java/org/scoula/register/util/RegisterRatingEvaluator.java
close #62 
등기부등본 등급 판단 로직을 구현했습니다.
판단 기준에 따라 `안전`, `보통`, `주의`, `위험`이 결정되게 됩니다.
`DatedCanceledItem` 인터페이스를 이용해 모든 요소들에서 날짜와 말소여부만 가져와 비교할 수 있게 구현했습니다.
테스트를 진행하여 등급이 잘 판단되는지 확인했습니다.
> [feat] 등기부등본 분석 등급 판단 로직 구현

- frontend/src/pages/referencecontracts/ReferenceContract.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
- frontend/src/pages/special-contracts/SpecialContractsRecommendation.vue
>close #67 
> 특약 예시 중복 선택 방지, 계약서 작성 빈 칸 유무 검사 후 작성 완료 확인, 특약 예시 페이지 이동 후 다시 계약서 작성 페이지로 왔을 때 기존에 있던 입력 값 유지
> 입력 값 저장(F5, 헤더의 다른 페이지로 갔다 왔을 때 초기화), 중복 선택 방지, 빈 칸 유무 검사
> <img width="489" height="782" alt="image" src="https://github.com/user-attachments/assets/7ec3dbc9-19e5-4572-80b8-403adf649a41" />
> <img width="775" height="1261" alt="image" src="https://github.com/user-attachments/assets/1e6d7ce3-b681-4fb8-9913-7bde34c87a02" />
> <img width="586" height="1288" alt="image" src="https://github.com/user-attachments/assets/35d056b3-1c98-4efa-bbff-8ce6e2b6a2e9" />
> <img width="1254" height="745" alt="image" src="https://github.com/user-attachments/assets/9ac46f73-4a16-49bd-b155-bb1840c073f5" />
> 관련 문서, 스크린샷, 또는 …
> [feat] 계약서 작성, 특약 추천 페이지 기능 개선

- backend/src/main/java/org/scoula/security/config/SecurityConfig.java
> [chore]: api 요청 임시 허용

- frontend/src/components/Header.vue
Closes #75 
상단바 호버기능 추가
상단바 호버기능 정상 작동
> [feat] 상단바 호버 기능 추가

- backend/src/main/java/org/scoula/checklist/controller/ChecklistController.java
- backend/src/main/java/org/scoula/checklist/domain/dto/ChecklistDTO.java
- backend/src/main/java/org/scoula/checklist/mapper/ChecklistMapper.java
- backend/src/main/java/org/scoula/checklist/service/ChecklistService.java
- backend/src/main/java/org/scoula/checklist/service/ChecklistServiceImpl.java
- backend/src/main/java/org/scoula/config/RootConfig.java
- backend/src/main/resources/org/scoula/checklist.mapper/ChecklistMapper.xml
관련된 이슈 : #10 
체크리스트 관련 엔티티, 서비스, 컨트롤러 추가
체크리스트 CRUD 기능 구현
DTO 및 매핑 로직 작성
모든 기존 테스트 통과
> [feat] 체크리스트 백엔드 기능 추가

- backend/build.gradle
- backend/database.sql
- backend/src/main/java/org/scoula/register/config/AwsS3Config.java
- backend/src/main/java/org/scoula/register/config/PropertyConfig.java
- backend/src/main/java/org/scoula/register/controller/AmazonS3Controller.java
- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/RegisterDTO.java
- backend/src/main/java/org/scoula/register/mapper/RegisterMapper.java
- backend/src/main/java/org/scoula/register/service/AwsS3Service.java
- backend/src/main/java/org/scoula/register/service/TabulaService.java
- backend/src/main/resources/org/scoula/register/mapper/RegisterMapper.xml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/finalReport.js
- frontend/src/components/AnalysisCards.vue
- frontend/src/components/PDFView.vue
- frontend/src/components/final-report/FinalChecklist.vue
- frontend/src/components/final-report/FinalGrade.vue
- frontend/src/components/final-report/FinalJeonse.vue
- frontend/src/components/final-report/charts/BarChart.vue
- frontend/src/components/final-report/charts/DonutChart.vue
- frontend/src/pages/FinalReportPage.vue
- frontend/src/pages/RegisterResult.vue
- frontend/src/pages/SafetyDiagnosis.vue
- frontend/src/router/index.js
- frontend/vite.config.js
close #80 #81 
- 등기부등본 분석 테이블에 저장한 뒤 불러오고 PDF.js로 해당 등기부등본을 보여줍니다.
- 등기부등본 저장 테이블을 없애고 등기부분석 테이블에 `filName` 컬럼을 추가해줬습니다.
- PDF 출력하는 부분 `PDFView.vue`, 분석 요소들을 출력하는 `AnalysisCard.vue`를 컴포넌트로 만들었습니다.
- 디자인은 대충 해놔서 다시 다듬도록 하겠습니다.
> [feat] S3 연동 및 등기부등본 분석 페이지 구현

- backend/database.sql
> [chore] user_id 복구

- backend/src/main/java/org/scoula/register/domain/dto/RegisterDTO.java
`RegisterDTO` 클래스 내에 분석날짜 변수명이 `analysis_date`로 정의되어 있어 `analysisDate`로 변경해주었습니다.
> [chore] RegisterDTO 분석날짜 변수명 camelcase로 변경

- frontend/src/pages/RegisterResult.vue
figma UI 처럼 수정
- 등기부 등본, 위험 요소 분석 부분 각각 스크롤 가능하도록 함.
> [feat] 결과 분석 페이지 수정

- backend/database.sql
- backend/src/main/java/org/scoula/register/util/RegisterUtils.java
- frontend/src/components/AnalysisCards.vue
- frontend/src/pages/RegisterResult.vue
- close #114 
- 위험 요소 카드 디자인 수정 피그마 디자인 대로 하려다 생각보다 가독성이 안 좋아 수정했습니다.
- 각 피해 사례 추가했습니다.
- 발견된 요소가 있어야 피해 사례가 보입니다.
- 디자인 적용 테스트 완료
- 디자인 혹시 별로면 말씀해주세요.
> [feat] 위험 요소 컴포넌트 디자인 수정

- frontend/src/router/index.js
Closes #116 
면책고지 페이지 상단 헤더바 제거
상단 헤더 제거됨
> [feat] 면책고지 페이지 상단 헤더바 제거

- backend/src/main/java/org/scoula/config/RootConfig.java
- backend/src/main/java/org/scoula/contract/controller/ContractController.java
- backend/src/main/java/org/scoula/contract/domain/ContractDTO.java
- backend/src/main/java/org/scoula/contract/mapper/ContractMapper.java
- backend/src/main/java/org/scoula/contract/service/ContractService.java
- backend/src/main/java/org/scoula/specialclause/controller/SpecialClauseController.java
- backend/src/main/java/org/scoula/specialclause/domain/SpecialClauseDTO.java
- backend/src/main/java/org/scoula/specialclause/mapper/SpecialClauseMapper.java
- backend/src/main/java/org/scoula/specialclause/service/SpecialClauseService.java
- backend/src/main/resources/org/scoula/contract/mapper/ContractMapper.xml
- backend/src/main/resources/org/scoula/specialclause/mapper/SpecialClauseMapper.xml
- frontend/src/pages/referencecontracts/ReferenceContract.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
- frontend/src/pages/special-contracts/SpecialContractsRecommendation.vue
> close #121
> 계약서 작성 시 - 모든 항목 작성, 특약 예시 선택 시 중복 선택 방지 점검
> 작성 완료 후 계약 완료 페이지에 결과 출력, 작성 완료 버튼 클릭 시 DB에 전송
> <img width="1253" height="612" alt="image" src="https://github.com/user-attachments/assets/81ad4152-c874-4a3c-beac-21ad7fddddc9" />
> <img width="722" height="461" alt="image" src="https://github.com/user-attachments/assets/fd9456e3-fd09-4e14-906a-7015630b438d" />
> <img width="1254" height="600" alt="image" src="https://github.com/user-attachments/assets/3aac05d8-f70f-4643-9ec4-dcf5007af326" />
> 현재 특약 예시에서 선택한 특약 사항들이 DB에 저장이 되지 않아서 추후에 수정 예정이니 참고만 해주세요
> [feat] 계약서 작성, 작성 완료 UI 개선 및 계약서 작성 DB와 백엔드 작업

- backend/src/main/java/org/scoula/oauth/controller/AccessController.java
- backend/src/main/java/org/scoula/oauth/controller/KakaoOAuthController.java
- backend/src/main/java/org/scoula/oauth/domain/DTO/KakaoUserDTO.java
- backend/src/main/java/org/scoula/oauth/mapper/UserMapper.java
- backend/src/main/java/org/scoula/oauth/service/KakaoOAuthServiceImpl.java
- backend/src/main/java/org/scoula/oauth/service/UserService.java
- backend/src/main/java/org/scoula/security/filter/JwtAuthenticationFilter.java
- backend/src/main/java/org/scoula/security/service/CustomUserDetailsService.java
- backend/src/main/java/org/scoula/security/util/JwtProcessor.java
- backend/src/main/resources/org/scoula/mapper/UserMapper.xml
- frontend/src/pages/MyPage.vue
- frontend/src/router/index.js
- frontend/src/stores/auth.js
> close #127
> jwt토큰에 subject을 kakaoId에서 userId로 변경하여 프론트부분에서 피니아로 바로 userId 사용 가능
> [Refactor] jwt토큰 subject 변경

- frontend/src/pages/RegisterResult.vue
- frontend/src/router/index.js
- close #135 
- 체크리스트로 넘어가기 버튼 및 반응형 디자인 추가
- 해당 등기부등본의 체크리스트로 넘어가고 체크리스트 완료시 저장되는 것도 확인 완료
- 반응형 디자인 추가로 웹이 작아졌을 때 좌우로 보이던 컨텐츠 위,아래로 보이게 추가
> [feat] 등기부등본 분석 페이지 체크리스트로 넘어가기 버튼 및 반응형 디자인 추가

- frontend/src/pages/RegisterResult.vue
- close #147 
- 등기부등본 분석 결과 페이지 내 동그라미 차트 최종 리포트와 동일한 두께, 색상으로 수정
- `안전`, `보통`, `주의`, `위험`에 따른 멘트 수정
- 사용자님 대신 유저 이름이 뜨게 수정
- 각 등급별 멘트가 맞게 뜨는지 테스트 완료했습니다.
> [style] 등기부등본 결과 페이지 등급 표시 부분 디자인 및 등급별 멘트 수정

- backend/database.sql
> [fix] 최종리포트 status 기본값 true 설정

- backend/build.gradle
- backend/database.sql
- backend/src/main/java/org/scoula/config/ObjectMapperConfig.java
- backend/src/main/java/org/scoula/finalreport/controller/FinalReportController.java
- backend/src/main/java/org/scoula/finalreport/dto/FinalReportSummaryDTO.java
- backend/src/main/java/org/scoula/finalreport/mapper/FinalReportMapper.java
- backend/src/main/java/org/scoula/finalreport/service/FinalReportService.java
- backend/src/main/java/org/scoula/finalreport/service/FinalReportServiceImpl.java
- backend/src/main/java/org/scoula/security/account/domain/CustomUser.java
- backend/src/main/resources/org/scoula/finalreport/mapper/FinalReportMapper.xml
- frontend/src/pages/FinalReportPage.vue
- frontend/src/pages/category/CategoryAll.vue
- frontend/src/pages/category/CategoryManager.vue
- frontend/src/pages/listpages/ReportListPage.vue
> close- #153 
> mypage 최종리포트 리스트 구현
> [feat] mypage 최종리포트 리스트 구현

- backend/database.sql
- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/domain/dto/RegisterDTO.java
- backend/src/main/java/org/scoula/register/mapper/RegisterMapper.java
- backend/src/main/java/org/scoula/register/service/TabulaService.java
- backend/src/main/resources/org/scoula/register/mapper/RegisterMapper.xml
- close #157 
- `status`의 디폴트 값 `true`로 설정
- `RegisterMapper`에 50일 이후 `status`를 `true` -> `false`로 변경하는 기능 추가
- `Scheduled` 정상적으로 동작되는지 확인 완료
> [feat] 등기부등본 분석 결과 50일 이후 true->false로 변경 기능 추가

- backend/src/main/java/org/scoula/contract/controller/ContractController.java
- backend/src/main/java/org/scoula/contract/mapper/ContractMapper.java
- backend/src/main/java/org/scoula/contract/service/ContractService.java
- backend/src/main/resources/org/scoula/contract/mapper/ContractMapper.xml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/listpages/ContractListPage.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
- frontend/src/router/index.js
> #153 (아직 안끝났습니다)
> 마이페이지에 계약서 부분 리스트 출력 및 목록 클릭시 화면 출력 모듈 추가 해서 npm install 하셔야 합니다
> [feat] html2canvas + jsPDF모듈 추가 및 마이페이지 계약서 부분 구현

- frontend/src/pages/FinalReportPage.vue
- frontend/src/pages/listpages/ContractListPage.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
> [feat] 게약서 마이페이지 다운로드 버튼 구현

- backend/src/main/resources/org/scoula/register/mapper/RegisterMapper.xml
- frontend/src/pages/checklist/Checklist.vue
- frontend/src/pages/checklist/Preview.vue
- frontend/src/stores/checklistStore.js
> 관련된 이슈: #10 
등기부등본 분석하지않은 사용자 체크리스트 로직 구현
remainingDays가 0일 이하일 경우 만료된 매물은 DB에서 삭제되므로 "만료되었습니다" 문구는 더 이상 출력하지 않도록 수정
매물 선택 여부에 따라 분기 처리 (selectedProperty.length === 0일 때 처리 추가)
> 모든 콘솔 오류 없음 / 수동 테스트 통과
> [feat] 매물선택 유무에따른 처리로직 구현

- frontend/src/pages/MyPage.vue
> [feat] 마이페이지 최종리포트 미리보기

- frontend/src/components/final-report/DiagnosisGradeInfoModal.vue
- frontend/src/components/final-report/FinalChecklist.vue
- frontend/src/components/final-report/FinalGrade.vue
- frontend/src/pages/FinalReportPage.vue
> [refactor] 최종 리포트 페이지 모바일 반응형 스타일링 개선 및 UX 개선

- backend/src/main/java/org/scoula/checklist/controller/ChecklistController.java
- backend/src/main/java/org/scoula/checklist/mapper/ChecklistMapper.java
- backend/src/main/java/org/scoula/checklist/service/ChecklistService.java
- backend/src/main/java/org/scoula/checklist/service/ChecklistServiceImpl.java
- backend/src/main/resources/org/scoula/checklistmapper/ChecklistMapper.xml
- frontend/src/pages/checklist/Preview.vue
> 관련된 이슈: #10 
> 만료되었습니다. 다시추가
> 오류없음
> [refactor] checklist 불필요한 코드 삭제

- frontend/src/pages/FinalReportPage.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
> [feat] 다운로드 버튼 클릭시 로딩 창 구현

- backend/src/main/java/org/scoula/jeonseRate/controller/LeaseDiagnosisController.java
- 전세가율 결과 조회 API (GET /api/diagnosis/result)에 Swagger 어노테이션 추가
- @ApiOperation, @ApiResponses 적용
- Swagger UI에서 문서 정상 표시 확인
> [refactor] 전세가율 분석 api에 Swagger 추가

- backend/database.sql
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
> <img width="1243" height="710" alt="image" src="https://github.com/user-attachments/assets/ec3605e8-0927-45aa-a898-78db72cf7b76" />
> [refactor]작성 완료 페이지 UI 및 m^2, 원 등 수정, DB 수정

- frontend/src/pages/listpages/ContractListPage.vue
> [fix] 다운로드 버튼 출력 오류 수정

- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
> [refactor] 계약서 작성 완료 페이지 UI 수정

- frontend/src/pages/FinalReportPage.vue
> [refactor] 다운로드 버튼 스타일 수정

- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
>  모달 안뜨도록 주석 처리
> 계약서 작성 완료 페이지에 모달 안뜸
> [chore] 모달 주석 처리

- frontend/src/pages/checklist/Checklist.vue
> 관련된 이슈 :#10
> 슬라이더 화살표겹치는거 개선, 문항이 wrapper밖으로 나가지않도록 개선
> 오류없음
> [style] 체크리스트화면 스타일개선

- frontend/src/pages/referencecontracts/ReferenceContract.vue
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
- frontend/src/router/index.js
Closes #197 
계약서 작성 화면 ui 수정
모두 통과
> [style] 계약서 작성 화면 ui 수정

- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
> [fix] 다운로드 버튼 색상 변경

- frontend/src/pages/SafetyDiagnosis.vue
전세 보증금 입력 시 억/만원 단위로 자동 환산하여 실시간으로 표시되도록 개선
> [feat] 전세 보증금 입력 개선

- frontend/src/components/Header.vue
> 로그인여부에따라 로그인/ 마이페이지 뜨게하기
> 오류없음
><img width="1399" height="711" alt="image" src="https://github.com/user-attachments/assets/37fc5d66-caa1-4e5f-a02c-e2e6643011f4" />
> [feat] 헤더 로그인여부에따라 다르게 뜨게하기

- frontend/src/pages/MyPage.vue
> [style] 로그아웃 스타일변경

- frontend/src/pages/referencecontracts/ReferenceContract.vue
- frontend/src/router/index.js
Closes #227 
계약서 작성 페이지 모달 ui 수정 및 페이지 ui 수정
모든테스트 성공
> [feat] 계약서 작성 페이지 모달 ui 수정 및 페이지 ui 수정

- backend/src/main/java/org/scoula/finalreport/service/FinalReportServiceImpl.java
- backend/src/main/java/org/scoula/register/util/RegisterUtils.java
- frontend/index.html
- close #229 
- 최종 리포트 위험 요소 말소 내역 필터링 적용
- 탐색 키워드 소유자 추가
- 사이트 이름 `Vite App` -> `HomeBuddy` 수정
- 말소 내역 필터링, 소유자 탐색 가능
> [fix] 최종 리포트 위험 요소 말소 내역 필터링 & 탐색 키워드 소유자 추가

- frontend/src/pages/special-contracts/SpecialContractsRecommendation.vue
- close #231 
- 선택한 특약 출력
- 추가하기 버튼 캐릭터에서 직관적으로 수정
- 특약리스트 부분 `max-height` 제거
- 테스트 완료
> [style] 특약 선택시 선택된 특약 확인 및 추가하기 버튼 수정

- backend/src/main/java/org/scoula/register/controller/TabulaController.java
- backend/src/main/java/org/scoula/register/util/RegisterUtils.java
- frontend/src/pages/SafetyDiagnosis.vue
- close #237 
- 사용자가 입력한 상세주소를 기반으로 해당 층의 면적을 읽어옵니다.
- 읽어오는데 실패하면 해당 모달창이 뜨며 면적을 입력하게 합니다.
- 면적 읽는 경우, 못 읽는 경우 테스트 완료
> [feat] 면적 정보 불러오기 구현

- frontend/src/pages/GlossaryBook.vue
Closes #251 
용어집 ui 수정
카드 배열 3개 고정 및 좌우 여백 확보
모든 케이스 통과
> [style] 용어집 ui 수정

- frontend/src/pages/RegisterResult.vue
> close #247 
- 등급 원 두께, 크기, 글씨 확대
- 등급 안내 문구 크기 키우고, ui 수정
- 분석 결과 좌우 섹션 레이아웃 조정
---
> [style] RegisterResult.vue 레이아웃/스타일 조정

- frontend/src/components/Header.vue
> 관련된 이슈: #256 
>헤더 피드백부분 수정
> 오류없음
> [fix] 헤더 피드백부분 수정

- frontend/src/pages/checklist/Checklist.vue
- frontend/src/stores/checklistStore2.js
> 피드백부분 수정
왼쪽 계약서 이미지 크기 확대, 체크리스트 중요도 표시 추가하기. 확인 완료 버튼 위치  조정
> 오류없음
> [fix] 체크리스트 피드백부분 수정

- backend/src/main/java/org/scoula/oauth/controller/KakaoOAuthController.java
- backend/src/main/java/org/scoula/oauth/service/KakaoOAuthService.java
- backend/src/main/java/org/scoula/oauth/service/KakaoOAuthServiceImpl.java
- backend/src/main/java/org/scoula/security/config/SecurityConfig.java
- frontend/src/api/finalReport.js
- frontend/src/pages/HomePage.vue
- frontend/src/pages/MyPage.vue
- frontend/src/pages/login/KakaoCallback.vue
> close #263 
> 기존 회원탈퇴를 하려면 세션스토리지에 카카오 액세스 토큰을 저장해야하는데 그럼 XSS 공격으로 탈취 위험 존재하여 프론트에 저장안하고 백단에서 회원탈퇴 처리하도록 리팩토링
+ 경로별 접근권한 설정
> [refactor] 회원탈퇴 리팩토링

- backend/src/main/java/org/scoula/contract/controller/ContractController.java
- backend/src/main/java/org/scoula/finalreport/controller/FinalReportController.java
- backend/src/main/java/org/scoula/oauth/controller/AccessController.java
- backend/src/main/java/org/scoula/security/config/SecurityConfig.java
- backend/src/main/java/org/scoula/security/util/AccessChecker.java
- frontend/src/pages/listpages/ReportListPage.vue
- frontend/src/router/index.js
> [Feat] accesschecker

- backend/src/main/java/org/scoula/contract/controller/ContractController.java
- frontend/src/pages/referencecontracts/ReferenceContractSuccess.vue
- frontend/src/router/index.js
> [fix] 오류 수정
